disabled_rules: # rule identifiers turned on by default to exclude from running
  - vertical_whitespace
  - trailing_whitespace
  - trailing_newline

# included: # paths to include during linting. `--path` is ignored if present.
  # - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast:
  severity: warning

force_try:
  severity: warning

line_length: 
  warning: 110
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  
type_body_length:
  warning: 300
  error: 400

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone
  
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded:
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)

